version: "3.3"
services:
  server:
    build: ./
    volumes:
      - ./src/:/src
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 -u /src/server.py
    environment:
      - MYID=
      - BEARER=
    ports:
      - "80:80"

  terminator:
    build: ./
    volumes:
      - ./src/:/src
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 -u /src/terminator.py
